config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'orders#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :menus, only: :show do
        resources :menu_items, only: :index
      end
      resources :orders, only: [:index, :show, :update], shallow: true do
        resources :order_items, only: :create, shallow: true do
          member do
            patch 'cancel'
          end
          resources :reviews, only: [:create, :update], shallow: true
        end
      end
    end
  end

  resources :menus, only: [ :show, :create, :index ] do
    resources :menu_items, only: :create, shallow: true do
      member do
        patch 'active'
      end
    end
  end

  resources :customers, only: :index do
    collection do
      get :authenticate
    end
  end

  resources :orders, only: [ :index, :show, :create, :update ]

  resources :menu_items, except: [ :destroy, :create ]

  resources :order_items, only: :index do
    member do
      patch 'served'
    end
  end

end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu
  belongs_to :item
  # has_many :order_items, dependent: :destroy
  # has_many :reviews, through: :order_items
  accepts_nested_attributes_for :item, reject_if: :all_blank
end

app/controllers/api/v1/menu_items_controller.rb
class Api::V1::MenuItemsController < Api::V1::BaseController
  def index
    dishes = policy_scope(MenuItem).includes(:reviews)

    # Sends all the dishes to a service for formatting

    @categorized = MenuFormatter.call(dishes)
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: [:show, :edit, :update, :active]

  def index
    #Handles search if a search has been made

    if params[:search].present?
      @menu_items = MenuItem.search_by_name_and_description(params[:search][:query])
    else
      @menu_items = MenuItem.all
    end
  end

  def show; end

  def new
    @menu_item = MenuItem.new()
  end


  def create
    @menu_item = MenuItem.new(menu_item_params)
    @menu_item.menu = params[:menu_id]
    if @menu_item.save
      redirect_to menu_item_path(@menu_item)
    else
      render :new
    end
  end

  def edit; end

  def update
    @menu_item.update(menu_item_params)
    if @menu_item.save
      redirect_to menu_item_path(@menu_item)
    else
      render :edit
    end
  end

  def active
    @menu_item.active = !@menu_item.active
    if @menu_item.save
      respond_to do |format|
        format.js
      end
    end
  end

  private

  def set_menu_item
    @menu_item = MenuItem.find(params[:id])
  end

  def menu_item_params
    params.require(:menu_item).permit(:name, :description, :category, :price)
  end
end

app/views/menu_items/_menu_item.html.erb
<div class="staff-menu-item-card <%= "inactive" unless item.active %> shadow">
  <%= cl_image_tag item.photo.key, crop: :fill, class: 'menu-item-image' %>
  <div class="menu-item-active-button">
    <% if item.active %>
      <%= link_to  active_menu_item_path(item), method: :patch, remote: true do %>
        <i class='fas fa-toggle-on'></i>
      <% end %>
    <% else %>
      <%= link_to  active_menu_item_path(item), method: :patch, remote: true do %>
        <i class='fas fa-toggle-off'></i>
      <% end %>
    <% end %>
  </div>
  <div class="menu-item-info row">
    <div class="menu-item-info-details col-8">
      <p><b><%= item.name %></b></p>
      <p><%= item.description %></p>
    </div>
    <div class="col-4">
      <div class="row">
        <div class="d-flex align-items-center justify-content-end col">
          <p><%= item.category %></p>
        </div>
      </div>
      <div class="row">
        <div class="d-flex align-items-center justify-content-end col">
          <p>¥<%= item.price %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/menu_items/active.js.erb
var card = document.getElementById("staff-menu-item-card-<%= @menu_item.id %>");
card.innerHTML = " <%= escape_javascript(render partial: 'menu_item', locals: { item: @menu_item } ) %> ";
card.classList.toggle("inactive");

app/views/menu_items/index.html.erb
<!-- <div class="row">
  <div class="menu-item-toolbar">
    <%= simple_form_for :query, url: menu_items_path, method: :get do |f| %>
      <div class="input-group">
        <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Find your products..." />
        <div class="input-group-append">
          <button name="button" type="submit" class="btn btn-success"><i class="fas fa-search"></i></button>
        </div>
      </div>
    <% end %>
  </div>
</div> -->

<div class="row" id="staff-menu-item-cards">
  <% @menu_items.each do |item| %>
    <div class="col-4 py-2" id="staff-menu-item-card-<%= item.id %>">
      <%= render 'menu_item', item: item %>
    </div>
  <% end %>
</div>

app/views/menu_items/show.html.erb
<h3>Menu Item <%= @menu_item.id %></h3>
<p><%= @menu_item.name %></p>
<p><%= @menu_item.description %></p>
<p><%= @menu_item.category %></p>
<p><%= @menu_item.price %></p>