config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'orders#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :menus, only: :show do
        resources :menu_items, only: :index
      end
      resources :orders, only: [:index, :show, :update], shallow: true do
        resources :order_items, only: :create, shallow: true do
          member do
            patch 'cancel'
          end
          resources :reviews, only: [:create, :update], shallow: true
        end
      end
    end
  end

  resources :menus, only: [ :show, :create, :index ] do
    resources :menu_items, only: :create, shallow: true do
      member do
        patch 'active'
      end
    end
  end

  resources :customers, only: :index do
    collection do
      get :authenticate
    end
  end

  resources :orders, only: [ :index, :show, :create, :update ]

  resources :menu_items, except: [ :destroy, :create ]

  resources :order_items, only: :index do
    member do
      patch 'served'
    end
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="my-navbar">
  <% if user_signed_in? %>
    <div class="user-profile">
      <div class="user-image">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar-large"%>
      </div>
      <div class="user-details">
        <h4>Hello, <%= current_user.email %></h4>
      </div>
    </div>
    <div class="my-nav-item">
      <%= link_to destroy_user_session_path, method: :delete, class: 'my-nav-link' do %>
        <i class="fas fa-sign-out-alt"></i>
      <% end %>
    </div>

    <div class="app-nav text-center">
      <%= link_to orders_path, class: 'new-customer shadow offset-2 col-8' do %>
        <i class="fas fa-user-friends"></i>
      <% end %>
      <%= link_to order_items_path, class: 'orders mt-3 shadow offset-2 col-8'  do %>
        <i class="fas fa-concierge-bell"></i>
      <% end %>
      <%= link_to menus_path, class: 'menus mt-3 shadow offset-2 col-8' do %>
        <i class="fas fa-clipboard-list"></i>
      <% end %>
      <%= link_to menu_items_path, class: 'menu-items mt-3 shadow offset-2 col-8' do %>
          <i class="fas fa-hamburger"></i>
      <% end %>
    </div>

  <% else %>
    <div class="my-nav-item">
      <%= link_to "Login", new_user_session_path, class: "my-nav-link" %>
    </div>
  <% end %>
</div>