config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'orders#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :menus, only: :show do
        resources :menu_items, only: :index
      end
      resources :orders, only: [:index, :show, :update], shallow: true do
        resources :order_items, only: :create, shallow: true do
          member do
            patch 'cancel'
          end
          resources :reviews, only: [:create, :update], shallow: true
        end
      end
    end
  end

  resources :menus, only: [ :show, :create, :index ] do
    resources :menu_items, only: :create, shallow: true do
      member do
        patch 'active'
      end
    end
  end

  resources :customers, only: :index do
    collection do
      get :authenticate
    end
  end

  resources :orders, only: [ :index, :show, :create, :update ]

  resources :menu_items, except: [ :destroy, :create ]

  resources :order_items, only: :index do
    member do
      patch 'served'
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :menu_items, through: :order_items
  validates :table, presence: true, uniqueness: true
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::V1::BaseController
  acts_as_token_authentication_handler_for User

  def index
    orders = policy_scope(Order)
    render json: orders
  end

  def show
    user = User.find_by(email: request.headers["X-User-Email"])
    @order = Order.where(user: user)
                  .includes(:order_items)
                  .where(order_items: {status: ['pending', 'served']})
                  .includes(:menu_items)
                  .first
    @order = Order.where(user: user).first if @order.nil?
    authorize @order
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: :update

  def index
    @orders = Order.where(paid: false).includes(:menu_items)
    @order = Order.new()
  end

  def show
    @order = Order.where(id: params[:id]).includes(:user).first
    base_url = 'https://restaurant-covid-api-app.herokuapp.com/customers/authenticate'

    # Makes qr code for a customer with query strings for future authentication

    qrcode = RQRCode::QRCode.new("#{base_url}?user_email=#{@order.user.email}&user_token=#{@order.user.authentication_token}")

    # Changes qr code into a SVG

    @svg = qrcode.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 6,
      standalone: true
    )
  end

  def create
    @order = Order.new(order_params)
    @order.user = User.create(role: 'customer', email: "#{@order.table}#{(0...8).map { (65 + rand(26)).chr }.join}@gmail.com", password: 'password')
    if @order.save
      redirect_to orders_path
    else
      render :index
    end
  end

  def update
    @order.update(paid: true)
    if @order.save
      redirect_to orders_path
    else
      render :index
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:table)
  end
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
<%= f.input :table %>
<%= f.submit 'serve', class: 'btn btn-outline-secondary' %>
<% end %>

app/views/orders/_orders.html.erb
<% orders.each do |order| %>
  <div class="table-row">
    <div class="table-cell"><%= link_to order.table, order_path(order) %></div>
    <div class="table-cell">¥<%= order.total_price %></div>
    <div class="table-cell"><%= order.order_items.count %></div>
    <div class="table-cell">
      <%= link_to order_path(order), remote: true, method: :patch do %>
        <div class="btn btn-primary btn-sm">
          <p>Paid</p>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/orders/index.html.erb
<h1>Create a new customer!</h1>
<%= render 'form' %>

<h1 class="pt-3">Customers</h1>

<div class="customer-table">
  <div class="table-row">
    <div class="table-header">Table</div>
    <div class="table-header">Total Price</div>
    <div class="table-header">Number of Items</div>
    <div class="table-header">Controls</div>
  </div>
  <%= render 'orders', orders: @orders %>
</div>

app/views/orders/show.html.erb
<div class="customer-order-container">
  <h3>Customer Order <small>(Table: <%= @order.table %> Price: <%= @order.total_price %>)</small></h3>

  <p class="py-3"><%= @svg.html_safe %></p>

  <div class="customer-table">
    <div class="table-head">
      <div class="table-row">
        <div class="table-header">Dish</div>
        <div class="table-header">Updated</div>
        <div class="table-header">Status</div>
        <div class="table-header">Control</div>
      </div>
    </div>
    <div class="table-body" id="orders" data-order-id="<%= @order.id %>">
      <% @order.order_items.order(updated_at: :desc).each do |item| %>
        <%= render 'order_items/order_item', item: item, control: true %>
      <% end %>
    </div>
  </div>
</div>