config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'orders#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :menus, only: :show do
        resources :menu_items, only: :index
      end
      resources :orders, only: [:index, :show, :update], shallow: true do
        resources :order_items, only: :create, shallow: true do
          member do
            patch 'cancel'
          end
          resources :reviews, only: [:create, :update], shallow: true
        end
      end
    end
  end

  resources :menus, only: [ :show, :create, :index ] do
    resources :menu_items, only: :create, shallow: true do
      member do
        patch 'active'
      end
    end
  end

  resources :customers, only: :index do
    collection do
      get :authenticate
    end
  end

  resources :orders, only: [ :index, :show, :create, :update ]

  resources :menu_items, except: [ :destroy, :create ]

  resources :order_items, only: :index do
    member do
      patch 'served'
    end
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  has_one :review
  belongs_to :menu_item
  belongs_to :order
end

app/controllers/api/v1/order_items_controller.rb
class Api::V1::OrderItemsController < Api::V1::BaseController
  acts_as_token_authentication_handler_for User, only: %i[create cancel]

  def create
    user = User.find_by(email: request.headers["X-User-Email"])
    @order = Order.find_by(user: user)
    @order_item = OrderItem.new(order_params)
    @order_item.order = @order
    authorize @order_item
    if @order_item.save
      @order.total_price += @order_item.menu_item.price
      @order.save
      OrderChannel.broadcast_to(
        @order,
        render_to_string(partial: "order_items/order_item", locals: { item: @order_item, control: false  }, formats: [:html])
      )
      redirect_to api_v1_order_path(@order_item.order)
    else
      render_error
    end
  end

  def cancel
    @order_item = OrderItem.find(params[:id])
    @order_item.status = 'cancelled'
    if @order_item.save
      @order = @order_item.order
      @order.total_price -= @order_item.menu_item.price
      @order.save
      OrderChannel.broadcast_to(
        @order,
        render_to_string(partial: "order_items/order_item", locals: { item: @order_item, control: false }, formats: [:html])
      )
      authorize @order_item
      render json: @order_item
    else
      render_error
    end
  end

  private

  def order_params
    params.require(:order_item).permit(:order_id, :menu_item_id, :status)
  end

  def render_error
    render json: { errors: @order_item.errors.full_messages },
      status: :unprocessable_entity
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def index
    @orders = Order.where(paid: false)
  end

  def served
    @order_item = OrderItem.find(params[:id])
    @order_item.status = 'served'
    if @order_item.save
      @order = @order_item.order
      @order_item
    end
    redirect_to order_path(@order)
  end
end

app/views/order_items/_order_item.html.erb
<div class="table-row" data-order-id="<%= item.order.id %>">
  <div class="table-cell">
    <p><%= item.menu_item.name %></p>
  </div>
  <div class="table-cell">
    <p><%= time_ago_in_words(item.updated_at) %></p>
  </div>
  <div class="table-cell">
    <p><%= item.status %></p>
  </div>
  <% if control == true && item.status == 'pending' %>
    <div class="table-cell">
      <%= link_to served_order_item_path(item), remote: true, method: :patch do %>
        <div class="btn btn-primary btn-sm">
          <p>Served</p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/order_items/index.html.erb
<div class="order-container">
  <% @orders.each do |order| %>
    <div class="order-table col-5">
      <div class="table-head">
        <div class="table-row">
          <div class="table-header-long"> <%= link_to "Table: #{order.table}", order_path(order) %></div>
        </div>
        <div class="table-row">
          <div class="table-header">Dish</div>
          <div class="table-header">Updated</div>
          <div class="table-header">Status</div>
        </div>
      </div>
      <div class="table-body" id="orders" data-order-id="<%= order.id %>">
        <% order.order_items.order(updated_at: :desc).limit(15).each do |item| %>
          <%= render 'order_item', item: item, control: false %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>